# Generated by Django 4.2.5 on 2023-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_notes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
